build_dlls get correct version from tag

diff --git a/.github/workflows/build_dlls.yml b/.github/workflows/build_dlls.yml
--- a/.github/workflows/build_dlls.yml
+++ b/.github/workflows/build_dlls.yml
@@ -3,7 +3,7 @@ name: Build and Publish DLLs
 on:
   push:
     tags:
-      - "*"
+      - 'v*.*.*'
 
 jobs:
   build_and_publish:
@@ -11,13 +11,20 @@ jobs:
 
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
         with:
           ref: ${{ github.sha }}
 
       - name: Extract version digits from tag
         id: extract_version
-        run: echo "VERSION=$(echo ${{ github.ref_name }} | sed 's/refs\/tags\/v//')" >> $GITHUB_STATE
+        run: |
+          $TAG="${{ github.ref_name }}"
+          if (-not ($TAG -match '^v\d+\.\d+\.\d+(\w*)$')) {
+            echo "Invalid tag format: $TAG"
+            exit 1
+          }
+          $version=$TAG.Substring(1)
+          echo "VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
 
       - name: Install .NET Core SDK
         uses: actions/setup-dotnet@v2
